version: '3.4'

services:
  catalog:
    image: catalog
    build:
      context: .
      dockerfile: Catalog/Dockerfile
    ports:
      - "5181:80"
      - "7110:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  postgres:
    image: postgres:latest
    container_name: catalogdb
    environment:
      POSTGRES_DB: gametrading_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata: