version: '3.4'

services:
  catalog:
    container_name: catalog
    image: catalog
    build:
      context: .
      dockerfile: src/Catalog/Dockerfile
    ports:
      - "5181:80"
      - "7110:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - postgres

  basket:
    container_name: basket
    image: basket
    build: 
      context: .
      dockerfile: src/Basket/Dockerfile
    ports:
      - "5062:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - basket.data

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./vue-frontend
      dockerfile: ./Dockerfile
    ports:
      - "8081:80"

  postgres:
    image: postgres:latest
    container_name: catalogdb
    environment:
      POSTGRES_DB: gametrading_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  
  basket.data:
    image: redis
    ports:
      - "6379:6379"


volumes:
  pgdata: